// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Base.proto

package cn.laoshini.dk.net.msg;

public final class BaseProtobufMessage {
    private BaseProtobufMessage() {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface BaseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Base)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 协议号
         * </pre>
         *
         * <code>int32 cmd = 1;</code>
         */
        int getCmd();

        /**
         * <pre>
         * 返回码，正常返回为200
         * </pre>
         *
         * <code>int32 code = 2;</code>
         */
        int getCode();

        /**
         * <pre>
         * 预留扩展参数
         * </pre>
         *
         * <code>string params = 3;</code>
         */
        String getParams();

        /**
         * <pre>
         * 预留扩展参数
         * </pre>
         *
         * <code>string params = 3;</code>
         */
        com.google.protobuf.ByteString getParamsBytes();

        /**
         * <pre>
         * 扩展对象，具体的消息内容，类似于proto2中的extensions
         * </pre>
         *
         * <code>.google.protobuf.Any detail = 4;</code>
         */
        boolean hasDetail();

        /**
         * <pre>
         * 扩展对象，具体的消息内容，类似于proto2中的extensions
         * </pre>
         *
         * <code>.google.protobuf.Any detail = 4;</code>
         */
        com.google.protobuf.Any getDetail();

        /**
         * <pre>
         * 扩展对象，具体的消息内容，类似于proto2中的extensions
         * </pre>
         *
         * <code>.google.protobuf.Any detail = 4;</code>
         */
        com.google.protobuf.AnyOrBuilder getDetailOrBuilder();
    }

    /**
     * Protobuf type {@code Base}
     */
    public static final class Base extends com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Base)
            BaseOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Base.newBuilder() to construct.
        private Base(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Base() {
            params_ = "";
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        private Base(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
                    .newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            cmd_ = input.readInt32();
                            break;
                        }
                        case 16: {

                            code_ = input.readInt32();
                            break;
                        }
                        case 26: {
                            String s = input.readStringRequireUtf8();

                            params_ = s;
                            break;
                        }
                        case 34: {
                            com.google.protobuf.Any.Builder subBuilder = null;
                            if (detail_ != null) {
                                subBuilder = detail_.toBuilder();
                            }
                            detail_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(detail_);
                                detail_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        default: {
                            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return BaseProtobufMessage.internal_static_Base_descriptor;
        }

        @Override
        protected FieldAccessorTable internalGetFieldAccessorTable() {
            return BaseProtobufMessage.internal_static_Base_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(Base.class, Builder.class);
        }

        public static final int CMD_FIELD_NUMBER = 1;
        private int cmd_;

        /**
         * <pre>
         * 协议号
         * </pre>
         *
         * <code>int32 cmd = 1;</code>
         */
        public int getCmd() {
            return cmd_;
        }

        public static final int CODE_FIELD_NUMBER = 2;
        private int code_;

        /**
         * <pre>
         * 返回码，正常返回为200
         * </pre>
         *
         * <code>int32 code = 2;</code>
         */
        public int getCode() {
            return code_;
        }

        public static final int PARAMS_FIELD_NUMBER = 3;
        private volatile Object params_;

        /**
         * <pre>
         * 预留扩展参数
         * </pre>
         *
         * <code>string params = 3;</code>
         */
        public String getParams() {
            Object ref = params_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                params_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 预留扩展参数
         * </pre>
         *
         * <code>string params = 3;</code>
         */
        public com.google.protobuf.ByteString getParamsBytes() {
            Object ref = params_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                params_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int DETAIL_FIELD_NUMBER = 4;
        private com.google.protobuf.Any detail_;

        /**
         * <pre>
         * 扩展对象，具体的消息内容，类似于proto2中的extensions
         * </pre>
         *
         * <code>.google.protobuf.Any detail = 4;</code>
         */
        public boolean hasDetail() {
            return detail_ != null;
        }

        /**
         * <pre>
         * 扩展对象，具体的消息内容，类似于proto2中的extensions
         * </pre>
         *
         * <code>.google.protobuf.Any detail = 4;</code>
         */
        public com.google.protobuf.Any getDetail() {
            return detail_ == null ? com.google.protobuf.Any.getDefaultInstance() : detail_;
        }

        /**
         * <pre>
         * 扩展对象，具体的消息内容，类似于proto2中的extensions
         * </pre>
         *
         * <code>.google.protobuf.Any detail = 4;</code>
         */
        public com.google.protobuf.AnyOrBuilder getDetailOrBuilder() {
            return getDetail();
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (cmd_ != 0) {
                output.writeInt32(1, cmd_);
            }
            if (code_ != 0) {
                output.writeInt32(2, code_);
            }
            if (!getParamsBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, params_);
            }
            if (detail_ != null) {
                output.writeMessage(4, getDetail());
            }
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            if (cmd_ != 0) {
                size += com.google.protobuf.CodedOutputStream.computeInt32Size(1, cmd_);
            }
            if (code_ != 0) {
                size += com.google.protobuf.CodedOutputStream.computeInt32Size(2, code_);
            }
            if (!getParamsBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, params_);
            }
            if (detail_ != null) {
                size += com.google.protobuf.CodedOutputStream.computeMessageSize(4, getDetail());
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Base)) {
                return super.equals(obj);
            }
            Base other = (Base) obj;

            if (getCmd() != other.getCmd())
                return false;
            if (getCode() != other.getCode())
                return false;
            if (!getParams().equals(other.getParams()))
                return false;
            if (hasDetail() != other.hasDetail())
                return false;
            if (hasDetail()) {
                if (!getDetail().equals(other.getDetail()))
                    return false;
            }
            if (!unknownFields.equals(other.unknownFields))
                return false;
            return true;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + CMD_FIELD_NUMBER;
            hash = (53 * hash) + getCmd();
            hash = (37 * hash) + CODE_FIELD_NUMBER;
            hash = (53 * hash) + getCode();
            hash = (37 * hash) + PARAMS_FIELD_NUMBER;
            hash = (53 * hash) + getParams().hashCode();
            if (hasDetail()) {
                hash = (37 * hash) + DETAIL_FIELD_NUMBER;
                hash = (53 * hash) + getDetail().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static Base parseFrom(java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Base parseFrom(java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Base parseFrom(com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Base parseFrom(com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Base parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Base parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Base parseFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static Base parseFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Base parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
        }

        public static Base parseDelimitedFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static Base parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static Base parseFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(Base prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code Base}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Base)
                BaseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return BaseProtobufMessage.internal_static_Base_descriptor;
            }

            @Override
            protected FieldAccessorTable internalGetFieldAccessorTable() {
                return BaseProtobufMessage.internal_static_Base_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(Base.class, Builder.class);
            }

            // Construct using cn.laoshini.dk.net.msg.BaseProtobufMessage.Base.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                }
            }

            @Override
            public Builder clear() {
                super.clear();
                cmd_ = 0;

                code_ = 0;

                params_ = "";

                if (detailBuilder_ == null) {
                    detail_ = null;
                } else {
                    detail_ = null;
                    detailBuilder_ = null;
                }
                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return BaseProtobufMessage.internal_static_Base_descriptor;
            }

            @Override
            public Base getDefaultInstanceForType() {
                return Base.getDefaultInstance();
            }

            @Override
            public Base build() {
                Base result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public Base buildPartial() {
                Base result = new Base(this);
                result.cmd_ = cmd_;
                result.code_ = code_;
                result.params_ = params_;
                if (detailBuilder_ == null) {
                    result.detail_ = detail_;
                } else {
                    result.detail_ = detailBuilder_.build();
                }
                onBuilt();
                return result;
            }

            @Override
            public Builder clone() {
                return super.clone();
            }

            @Override
            public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
                return super.setField(field, value);
            }

            @Override
            public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @Override
            public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
                    Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
                return super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Base) {
                    return mergeFrom((Base) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Base other) {
                if (other == Base.getDefaultInstance())
                    return this;
                if (other.getCmd() != 0) {
                    setCmd(other.getCmd());
                }
                if (other.getCode() != 0) {
                    setCode(other.getCode());
                }
                if (!other.getParams().isEmpty()) {
                    params_ = other.params_;
                    onChanged();
                }
                if (other.hasDetail()) {
                    mergeDetail(other.getDetail());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                Base parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Base) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int cmd_;

            /**
             * <pre>
             * 协议号
             * </pre>
             *
             * <code>int32 cmd = 1;</code>
             */
            public int getCmd() {
                return cmd_;
            }

            /**
             * <pre>
             * 协议号
             * </pre>
             *
             * <code>int32 cmd = 1;</code>
             */
            public Builder setCmd(int value) {

                cmd_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 协议号
             * </pre>
             *
             * <code>int32 cmd = 1;</code>
             */
            public Builder clearCmd() {

                cmd_ = 0;
                onChanged();
                return this;
            }

            private int code_;

            /**
             * <pre>
             * 返回码，正常返回为200
             * </pre>
             *
             * <code>int32 code = 2;</code>
             */
            public int getCode() {
                return code_;
            }

            /**
             * <pre>
             * 返回码，正常返回为200
             * </pre>
             *
             * <code>int32 code = 2;</code>
             */
            public Builder setCode(int value) {

                code_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 返回码，正常返回为200
             * </pre>
             *
             * <code>int32 code = 2;</code>
             */
            public Builder clearCode() {

                code_ = 0;
                onChanged();
                return this;
            }

            private Object params_ = "";

            /**
             * <pre>
             * 预留扩展参数
             * </pre>
             *
             * <code>string params = 3;</code>
             */
            public String getParams() {
                Object ref = params_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    params_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * 预留扩展参数
             * </pre>
             *
             * <code>string params = 3;</code>
             */
            public com.google.protobuf.ByteString getParamsBytes() {
                Object ref = params_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                    params_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 预留扩展参数
             * </pre>
             *
             * <code>string params = 3;</code>
             */
            public Builder setParams(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                params_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 预留扩展参数
             * </pre>
             *
             * <code>string params = 3;</code>
             */
            public Builder clearParams() {

                params_ = getDefaultInstance().getParams();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 预留扩展参数
             * </pre>
             *
             * <code>string params = 3;</code>
             */
            public Builder setParamsBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                params_ = value;
                onChanged();
                return this;
            }

            private com.google.protobuf.Any detail_;
            private com.google.protobuf.SingleFieldBuilderV3<com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> detailBuilder_;

            /**
             * <pre>
             * 扩展对象，具体的消息内容，类似于proto2中的extensions
             * </pre>
             *
             * <code>.google.protobuf.Any detail = 4;</code>
             */
            public boolean hasDetail() {
                return detailBuilder_ != null || detail_ != null;
            }

            /**
             * <pre>
             * 扩展对象，具体的消息内容，类似于proto2中的extensions
             * </pre>
             *
             * <code>.google.protobuf.Any detail = 4;</code>
             */
            public com.google.protobuf.Any getDetail() {
                if (detailBuilder_ == null) {
                    return detail_ == null ? com.google.protobuf.Any.getDefaultInstance() : detail_;
                } else {
                    return detailBuilder_.getMessage();
                }
            }

            /**
             * <pre>
             * 扩展对象，具体的消息内容，类似于proto2中的extensions
             * </pre>
             *
             * <code>.google.protobuf.Any detail = 4;</code>
             */
            public Builder setDetail(com.google.protobuf.Any value) {
                if (detailBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    detail_ = value;
                    onChanged();
                } else {
                    detailBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <pre>
             * 扩展对象，具体的消息内容，类似于proto2中的extensions
             * </pre>
             *
             * <code>.google.protobuf.Any detail = 4;</code>
             */
            public Builder setDetail(com.google.protobuf.Any.Builder builderForValue) {
                if (detailBuilder_ == null) {
                    detail_ = builderForValue.build();
                    onChanged();
                } else {
                    detailBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <pre>
             * 扩展对象，具体的消息内容，类似于proto2中的extensions
             * </pre>
             *
             * <code>.google.protobuf.Any detail = 4;</code>
             */
            public Builder mergeDetail(com.google.protobuf.Any value) {
                if (detailBuilder_ == null) {
                    if (detail_ != null) {
                        detail_ = com.google.protobuf.Any.newBuilder(detail_).mergeFrom(value).buildPartial();
                    } else {
                        detail_ = value;
                    }
                    onChanged();
                } else {
                    detailBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <pre>
             * 扩展对象，具体的消息内容，类似于proto2中的extensions
             * </pre>
             *
             * <code>.google.protobuf.Any detail = 4;</code>
             */
            public Builder clearDetail() {
                if (detailBuilder_ == null) {
                    detail_ = null;
                    onChanged();
                } else {
                    detail_ = null;
                    detailBuilder_ = null;
                }

                return this;
            }

            /**
             * <pre>
             * 扩展对象，具体的消息内容，类似于proto2中的extensions
             * </pre>
             *
             * <code>.google.protobuf.Any detail = 4;</code>
             */
            public com.google.protobuf.Any.Builder getDetailBuilder() {

                onChanged();
                return getDetailFieldBuilder().getBuilder();
            }

            /**
             * <pre>
             * 扩展对象，具体的消息内容，类似于proto2中的extensions
             * </pre>
             *
             * <code>.google.protobuf.Any detail = 4;</code>
             */
            public com.google.protobuf.AnyOrBuilder getDetailOrBuilder() {
                if (detailBuilder_ != null) {
                    return detailBuilder_.getMessageOrBuilder();
                } else {
                    return detail_ == null ? com.google.protobuf.Any.getDefaultInstance() : detail_;
                }
            }

            /**
             * <pre>
             * 扩展对象，具体的消息内容，类似于proto2中的extensions
             * </pre>
             *
             * <code>.google.protobuf.Any detail = 4;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> getDetailFieldBuilder() {
                if (detailBuilder_ == null) {
                    detailBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                            getDetail(), getParentForChildren(), isClean());
                    detail_ = null;
                }
                return detailBuilder_;
            }

            @Override
            public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }

            // @@protoc_insertion_point(builder_scope:Base)
        }

        // @@protoc_insertion_point(class_scope:Base)
        private static final Base DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new Base();
        }

        public static Base getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Base> PARSER = new com.google.protobuf.AbstractParser<Base>() {
            @Override
            public Base parsePartialFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Base(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Base> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<Base> getParserForType() {
            return PARSER;
        }

        @Override
        public Base getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor internal_static_Base_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_Base_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

    static {
        String[] descriptorData = { "\n\nBase.proto\032\031google/protobuf/any.proto\""
                + "W\n\004Base\022\013\n\003cmd\030\001 \001(\005\022\014\n\004code\030\002 \001(\005\022\016\n\006pa"
                + "rams\030\003 \001(\t\022$\n\006detail\030\004 \001(\0132\024.google.prot"
                + "obuf.AnyB-\n\026cn.laoshini.dk.net.msgB\023Base" + "ProtobufMessageb\006proto3" };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            public com.google.protobuf.ExtensionRegistry assignDescriptors(
                    com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[] { com.google.protobuf.AnyProto.getDescriptor(), },
                assigner);
        internal_static_Base_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_Base_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Base_descriptor, new String[] { "Cmd", "Code", "Params", "Detail", });
        com.google.protobuf.AnyProto.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
